"""
Build Channel Registry — Batch 2 (C51–C101)
Generates rubrics/Dataset_Channel_Registry_Batch2.xlsx
matching the schema of the existing Batch 1 registry.
"""

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

CHANNELS = [
    # ── Threat Intelligence / Vendor ──────────────────────────────────────────
    {
        "Channel_ID": "C51",
        "Channel_Name": "SentinelOne",
        "Channel_URL": "https://www.youtube.com/@SentinelOne",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Threat briefings, ransomware family deep dives",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "SentinelLabs publishes detailed ransomware family reports; strong RaaS and affiliate model coverage.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C52",
        "Channel_Name": "Check Point Research",
        "Channel_URL": "https://www.youtube.com/@CheckPointSoftware",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Malware, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Threat briefings, actor profiling, family breakdowns",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "CPR produces frequent RaaS and ransomware group analyses; technically detailed.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C53",
        "Channel_Name": "Trend Micro",
        "Channel_URL": "https://www.youtube.com/@TrendMicro",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Threat briefings, attribution research, affiliate tracking",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Strong ransomware attribution and affiliate tracking content; vendor bias but technically solid.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C54",
        "Channel_Name": "WithSecure",
        "Channel_URL": "https://www.youtube.com/@WithSecure",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, TI, Malware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium–High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "IR case studies, adversary simulation research",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Formerly F-Secure; deep IR and adversary simulation research with strong technical credibility.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C55",
        "Channel_Name": "Rapid7",
        "Channel_URL": "https://www.youtube.com/@Rapid7",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Vulnerability Research",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Threat briefings, exploitation research, vulnerability analysis",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Strong on initial access exploitation used by ransomware operators; AttackerKB content relevant.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C56",
        "Channel_Name": "Malwarebytes",
        "Channel_URL": "https://www.youtube.com/@Malwarebytes",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Malware, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Ransomware family analyses, threat intel reports",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Ransomware-focused vendor; Malwarebytes ThreatDown publishes regular family breakdowns.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C57",
        "Channel_Name": "Group-IB",
        "Channel_URL": "https://www.youtube.com/@GroupIB",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Actor attribution, ransomware affiliate profiling, dark web intel",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Strong CIS/Russia-nexus ransomware actor coverage; unique dark web and affiliate intel perspective.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C58",
        "Channel_Name": "Prodaft",
        "Channel_URL": "https://www.youtube.com/@Prodaft",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Threat actor deep dives, ransomware group infiltration reports",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Publishes rare inside-access reports on ransomware group infrastructure; highly technical.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C59",
        "Channel_Name": "Anomali",
        "Channel_URL": "https://www.youtube.com/@Anomali",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Threat briefings, IOC analysis, weekly threat roundups",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Regular threat intelligence briefings; useful for IOC and campaign tracking context.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C60",
        "Channel_Name": "Kroll",
        "Channel_URL": "https://www.youtube.com/@KrollLLC",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (DFIR / Consulting)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Incident response case studies, ransomware trends",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Major IR consulting firm; quarterly threat landscape reports with strong ransomware focus.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C61",
        "Channel_Name": "NCC Group",
        "Channel_URL": "https://www.youtube.com/@NCCGroup",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Malware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Technical research talks, malware analysis",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Research-oriented security consultancy; publishes detailed vulnerability and malware research.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C62",
        "Channel_Name": "Emsisoft",
        "Channel_URL": "https://www.youtube.com/@Emsisoft",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Ransomware family analyses, decryptor releases, trend reports",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Exclusively ransomware-focused vendor; one of the leading sources for family-level technical detail and decryptor development.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C63",
        "Channel_Name": "Intezer",
        "Channel_URL": "https://www.youtube.com/@IntezerLabs",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Malware, TI",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Malware genetic analysis, code reuse tracking, family lineage",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Unique code-similarity approach to malware attribution; valuable for ransomware lineage and shared tooling across families.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C64",
        "Channel_Name": "ZeroFox",
        "Channel_URL": "https://www.youtube.com/@ZeroFox",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium–High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Dark web monitoring, ransomware leak site tracking, actor intelligence",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Specialises in external threat intelligence including ransomware extortion sites and threat actor communications.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C65",
        "Channel_Name": "ReliaQuest",
        "Channel_URL": "https://www.youtube.com/@ReliaQuest",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (MDR / Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium–High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "MDR case studies, threat briefings, ransomware trend reports",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "MDR platform vendor with regular ransomware coverage; useful for detection and response perspectives.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C66",
        "Channel_Name": "Binary Defense",
        "Channel_URL": "https://www.youtube.com/@BinaryDefense",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (DFIR / MDR)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Threat intel reports, IR case studies, active defence content",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Practitioner-heavy MDR firm; publishes threat intel alongside IR and detection content.",
        "Included (Yes/No)": "Pending",
    },

    # ── DFIR Practitioners & Individual Researchers ───────────────────────────
    {
        "Channel_ID": "C67",
        "Channel_Name": "13Cubed",
        "Channel_URL": "https://www.youtube.com/@13Cubed",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Independent",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, Malware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium–High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Memory forensics, disk triage, DFIR walkthroughs",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Richard Davis; one of the highest-quality practitioner DFIR channels. Deep technical walkthroughs of tools and artefacts used in ransomware intrusions.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C68",
        "Channel_Name": "HuskyHacks",
        "Channel_URL": "https://www.youtube.com/@HuskyHacks",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Independent",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Malware, Offensive Security",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Malware analysis, offensive tool walkthroughs",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Well-structured malware analysis content; useful for understanding attacker tooling used alongside ransomware.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C69",
        "Channel_Name": "TCM Security",
        "Channel_URL": "https://www.youtube.com/@TCMSecurityAcademy",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Independent",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Offensive Security, IR",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Attack chain walkthroughs, red team techniques, IR fundamentals",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "The Cyber Mentor; large audience with solid coverage of techniques used in ransomware intrusion chains (credential access, lateral movement).",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C70",
        "Channel_Name": "Josh Stroschein",
        "Channel_URL": "https://www.youtube.com/@jstrosch",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Independent",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Malware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Malware reverse engineering, unpacking, analysis walkthroughs",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Detailed static and dynamic malware analysis; useful for ransomware encryption and dropper analysis.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C71",
        "Channel_Name": "ANY.RUN",
        "Channel_URL": "https://www.youtube.com/@anyrun_app",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Malware Sandbox)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Malware, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Live malware detonations, ransomware behaviour analysis",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Interactive sandbox vendor; publishes ransomware execution walkthroughs with process tree and network activity detail.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C72",
        "Channel_Name": "Cado Security",
        "Channel_URL": "https://www.youtube.com/@CadoSecurity",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (DFIR)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Cloud IR case studies, ransomware in cloud environments",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Cloud-native DFIR vendor; unique coverage of ransomware targeting AWS, Azure, and GCP environments.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C73",
        "Channel_Name": "Cyb3rWard0g",
        "Channel_URL": "https://www.youtube.com/@Cyb3rWard0g",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Independent",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, Detection Engineering",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "ATT&CK detection engineering, threat hunting, Jupyter-based analysis",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Roberto Rodriguez; MITRE ATT&CK contributor. Excellent detection-layer content aligned with ransomware tactic coverage.",
        "Included (Yes/No)": "Pending",
    },

    # ── Conferences ───────────────────────────────────────────────────────────
    {
        "Channel_ID": "C74",
        "Channel_Name": "Virus Bulletin Conference",
        "Channel_URL": "https://www.youtube.com/@VirusBulletin",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Malware, Ransomware, TI",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Research talks, malware family analyses, threat actor profiling",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Dedicated anti-malware/threat intelligence conference; among the highest ransomware content density of any conference channel.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C75",
        "Channel_Name": "Hack In The Box (HITB)",
        "Channel_URL": "https://www.youtube.com/@HITBSecConf",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Security Research, Malware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Exploitation research, malware RE, adversary technique talks",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Premier international conference; strong malware and reverse engineering tracks with ransomware family content.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C76",
        "Channel_Name": "Wild West Hackin' Fest",
        "Channel_URL": "https://www.youtube.com/@WildWestHackinFest",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, Offensive Security",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium–High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "IR case studies, red/blue team techniques, ransomware response",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Practitioner-heavy conference with strong IR and blue team focus; good ransomware response content.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C77",
        "Channel_Name": "SecTor",
        "Channel_URL": "https://www.youtube.com/@SecTorCA",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, TI, Security Research",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Security research talks, IR and threat intelligence sessions",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Canada's premier security conference; enterprise-focused with solid IR and ransomware response content.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C78",
        "Channel_Name": "CactusCon",
        "Channel_URL": "https://www.youtube.com/@CactusCon",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Security Research, IR",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Security research talks, technical deep dives",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Regional conference with growing technical depth; useful supplementary coverage.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C79",
        "Channel_Name": "GrayHat Conference",
        "Channel_URL": "https://www.youtube.com/@GrayHatConference",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Security Research, Offensive Security",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Research-heavy talks, vulnerability and exploitation content",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Research-heavy conference; useful for exploitation techniques relevant to ransomware initial access.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C80",
        "Channel_Name": "ICS Village",
        "Channel_URL": "https://www.youtube.com/@ICSVillage",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, Ransomware, OT/ICS",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium–High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "OT/ICS security talks, ransomware impact on industrial systems",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "DEF CON village focused on ICS/OT; critical for ransomware-on-industrial-infrastructure coverage not found in mainstream channels.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C81",
        "Channel_Name": "Hack.lu Conference",
        "Channel_URL": "https://www.youtube.com/@hack_lu",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Malware, TI, Security Research",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "European security research, malware and threat intelligence talks",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Luxembourg-based European conference; strong malware and ransomware research from European practitioners.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C82",
        "Channel_Name": "Troopers Conference",
        "Channel_URL": "https://www.youtube.com/@TroopersConference",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Security Research, IR",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Enterprise security research, Active Directory, network defence",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "German conference; strong Active Directory and enterprise security content highly relevant to ransomware lateral movement.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C83",
        "Channel_Name": "BlueHat (Microsoft Security)",
        "Channel_URL": "https://www.youtube.com/@BlueHat",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Security Research, IR, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium–High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Microsoft-hosted security research talks, ransomware defence",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Microsoft's internal security conference; strong Windows-platform ransomware defence and response content.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C84",
        "Channel_Name": "CYBERWARCON",
        "Channel_URL": "https://www.youtube.com/@CYBERWARCON",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium–High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Nation-state actor analysis, ransomware-as-geopolitical-tool",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Focused on nation-state threats; covers ransomware used as geopolitical instrument (e.g. North Korea, Iran) often absent from other channels.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C85",
        "Channel_Name": "OffensiveCon",
        "Channel_URL": "https://www.youtube.com/@OffensiveCon",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Security Research, Offensive Security",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Low–Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Exploitation research, low-level vulnerability analysis",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Deep exploitation research; useful for understanding vulnerability classes used in ransomware initial access.",
        "Included (Yes/No)": "Pending",
    },

    # ── OT / ICS / Critical Infrastructure ───────────────────────────────────
    {
        "Channel_ID": "C86",
        "Channel_Name": "Claroty",
        "Channel_URL": "https://www.youtube.com/@Claroty",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (OT/ICS Security)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, Ransomware, OT/ICS",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium–High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "OT/ICS threat briefings, ransomware impact on industrial environments",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "OT/ICS security vendor; strong coverage of ransomware hitting manufacturing, energy, and utilities sectors.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C87",
        "Channel_Name": "Nozomi Networks",
        "Channel_URL": "https://www.youtube.com/@NozomiNetworks",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (OT/ICS Security)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Ransomware, OT/ICS",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "ICS threat intelligence, ransomware in operational technology",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "ICS-focused threat intel vendor; covers ransomware targeting operational technology networks.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C88",
        "Channel_Name": "S4 Conference",
        "Channel_URL": "https://www.youtube.com/@S4Conference",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "OT/ICS, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium–High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "ICS security talks, ransomware impact on critical infrastructure",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Premier ICS security conference (Dale Peterson); strong content on ransomware disrupting critical infrastructure — Colonial Pipeline-type incidents.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C89",
        "Channel_Name": "CISA",
        "Channel_URL": "https://www.youtube.com/@cisagov",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Government",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, Ransomware, TI",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Ransomware advisories, government guidance, StopRansomware briefings",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "US Cybersecurity and Infrastructure Security Agency; publishes official StopRansomware advisories and briefings — unique government perspective.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C90",
        "Channel_Name": "Waterfall Security",
        "Channel_URL": "https://www.youtube.com/@WaterfallSecurity",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (OT/ICS Security)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "OT/ICS, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Critical infrastructure defence, air-gap and OT security",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Air-gap and unidirectional gateway vendor; covers ransomware threat to critical infrastructure from a defence architecture perspective.",
        "Included (Yes/No)": "Pending",
    },

    # ── News & Analysis ───────────────────────────────────────────────────────
    {
        "Channel_ID": "C91",
        "Channel_Name": "Risky Business",
        "Channel_URL": "https://www.youtube.com/@RiskyBusiness",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Independent",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Weekly security news podcast, expert interviews on ransomware incidents",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Top infosec news show (Patrick Gray); ransomware incidents covered in depth with vendor and researcher guests. Lower technical density but strong contextual value.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C92",
        "Channel_Name": "Security Weekly",
        "Channel_URL": "https://www.youtube.com/@SecurityWeekly",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Independent",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Security Research",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Weekly shows with vendor and practitioner guests, threat roundups",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Long-running show (Paul Asadoorian); high volume with mixed technical depth — good for incident and actor name coverage.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C93",
        "Channel_Name": "Darknet Diaries",
        "Channel_URL": "https://www.youtube.com/@DarknetDiaries",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Independent",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Story-driven incident breakdowns, ransomware case narratives",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Jack Rhysider; narrative-style incident breakdowns including ransomware cases. Lower technical density but strong for actor name and family coverage.",
        "Included (Yes/No)": "Pending",
    },

    # ── Blue Team / Detection Engineering ────────────────────────────────────
    {
        "Channel_ID": "C94",
        "Channel_Name": "Florian Roth (Neo23x0)",
        "Channel_URL": "https://www.youtube.com/@cyb3rops",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Independent",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Malware, Detection Engineering",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "YARA rule writing, Sigma detection, threat hunting",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Author of YARA and key Sigma rules for ransomware detection; content highly aligned with detection engineering for ransomware IoCs.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C95",
        "Channel_Name": "Eric Zimmerman",
        "Channel_URL": "https://www.youtube.com/@EricZimmerman",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Independent",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, Malware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "DFIR tooling walkthroughs — KAPE, Timeline Explorer, artefact analysis",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Creator of KAPE and other DFIR tools widely used in ransomware incident response; tooling content directly relevant to ransomware artefact collection.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C96",
        "Channel_Name": "LetsDefend",
        "Channel_URL": "https://www.youtube.com/@LetsDefend",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Independent",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, Malware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "SOC training, ransomware investigation labs, blue team walkthroughs",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "SOC training platform with ransomware investigation scenario content; useful for detection and response language coverage.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C97",
        "Channel_Name": "Active Countermeasures (already C43)",
        "Channel_URL": "",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "— duplicate, already in Batch 1 —",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Duplicate check placeholder — remove or replace with new candidate before finalising.",
        "Included (Yes/No)": "Skip",
    },
    {
        "Channel_ID": "C98",
        "Channel_Name": "GuidePoint Security",
        "Channel_URL": "https://www.youtube.com/@GuidePointSecurity",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (DFIR / Consulting)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium–High",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "IR case studies, threat briefings, ransomware response",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Security consulting firm with dedicated ransomware response practice; regular threat intelligence and IR content.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C99",
        "Channel_Name": "ThreatConnect",
        "Channel_URL": "https://www.youtube.com/@ThreatConnect",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (Threat Intelligence)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Threat intel platform content, actor profiling, IOC analysis",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "TIP vendor with regular threat briefings including ransomware actor and campaign coverage.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C100",
        "Channel_Name": "Optiv",
        "Channel_URL": "https://www.youtube.com/@OptivSecurity",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Vendor (DFIR / Consulting)",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "IR, TI, Ransomware",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "IR case studies, threat briefings, ransomware trends",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Large security integrator with IR practice; publishes ransomware response and preparedness content.",
        "Included (Yes/No)": "Pending",
    },
    {
        "Channel_ID": "C101",
        "Channel_Name": "CanSecWest",
        "Channel_URL": "https://www.youtube.com/@CanSecWest",
        "Channel_Type (DFIR/Vendor/Conference/Independent)": "Conference",
        "Primary_Focus (IR, TI, Malware, Ransomware)": "Security Research, Offensive Security",
        "Estimated_Ransomware_Coverage (Low/Medium/High)": "Low–Medium",
        "Typical_Content (Talks, Case Studies, Deep Dives)": "Exploitation research, vulnerability analysis, security research talks",
        "Approx_Video_Count": None,
        "Years_Active": None,
        "Notes_on_Quality_or_Bias": "Pacific-rim conference; strong exploitation and vulnerability research useful for ransomware initial access context.",
        "Included (Yes/No)": "Pending",
    },
]

df = pd.DataFrame(CHANNELS)

out_path = ROOT / "rubrics" / "Dataset_Channel_Registry_Batch2.xlsx"
df.to_excel(out_path, index=False)
print(f"Saved {len(df)} rows → {out_path}")
print(f"\nChannel IDs: C51–C101  ({len(df)} candidates)")
print(f"Status breakdown:\n{df['Included (Yes/No)'].value_counts().to_string()}")
